### ISSUE TITLE
Run Inspec test with different user for example ORACLE

### ISSUE THREAD

**Issue by pratri07** [inspec/inspec#2005]
### Description

sql = oracledb_session( user: 'system', pass: 'XXXXXX', host: 'chefd.local.com', sid: 'chkdb', sqlplus_bin: '/u01/db12201/bin/sqlplus' )
describe sql.query('SELECT NAME FROM v$database;').row(0).column('name') do
  its('value') { should cmp 'CHKDB' }
end

I want to run above test as "Oracle" user, since it has to login to database and run sql query

It errors like below,
  SQL Column
     ∅  undefined method `[]' for nil:NilClass

I also tried below method,

inspec exec default/oratest.rb -t ssh://oracle@192.168.33.8 --password 'XXXX'
[DEPRECATED] use `password` option to supply password instead of `pass`
Could not execute the sql query 
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory

Profile: tests from default/oratest.rb
Version: (not specified)
Target:  ssh://oracle@192.168.33.8:22

  SQL Column
     ∅  undefined method `[]' for nil:NilClass

Test Summary: 0 successful, 1 failures, 0 skipped

If it is able to login as Oracle, it should adopt the profile settings and run given sql query, but it's not working.

Briefly describe the issue and the expected behavior

### InSpec and Platform Version

chef -v
Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.30.0

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
We had some issues with the oracle resource that has been fixed in latest inspec. Also you need to provide the resource a service now instead of a SID. Please have a look at https://www.inspec.io/docs/reference/resources/oracledb_session/

**Comment by pratri07** [comment]
Thanks chris, i will try with service. but can you please help me how can we run this test using oracle user? because oracle is installed and running part of oracle, not vagrant or root. Is there any way to run this with oracle? any modification needed in kitchen.yml file? 

Because i tried kitchen verify and inspec exec default/oratest.rb -t ssh://oracle@192.168.33.8 --password 'XXXX'

when i tried inspec exec login to oracle user, still it's not loading oracle user profile and setting all environments, so sqlplus is not able to run.

**Comment by adamleff** [comment]
@pratri07 InSpec runs as the user you tell it to, but you cannot tell it to use another user for a particular control/test.

If you're performing tests locally, simply become that user and then call `inspec exec /path/to/profile`

If you're performing tests remotely, you supply the user in your `--target` command line flag value... for example:

```shell
inspec exec /path/to/profile --target ssh://oracle@myhost.mycompany.biz --password passwordForTheOracleUser
```

Please note that InSpec does not acquire an interactive shell when performing remote scans, so certain files (such as files like `.bash_profile` and the files in `/etc/profile.d` are **not** evaluated. If this where the necessary environment variables such as ORACLE_HOME are specified, you may need to move those to a different file, such as `.bashrc`.

Thanks for using InSpec!

**Comment by pratri07** [comment]
thanks so much for your tips,

when i am running kitchen test it's trying to login as vagrant and oracle database is running as oracle user. i want to run this test as oracle. i shifted everything from .profile to .kshrc but still not working.

kitchen verify
-----> Starting Kitchen (v1.16.0)
-----> Verifying <default-centos-69>...
       Loaded tests from test/smoke/default 
[DEPRECATED] use `password` option to supply password instead of `pass`
Could not execute the sql query 
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory

Profile: tests from test/smoke/default
Version: (not specified)
_**Target:  ssh://vagrant@127.0.0.1:2200**_


  Port 1521
     ✔  should not be listening
  User oracle
     ✔  should exist
     ✔  uid should eq 201
     ✔  shell should eq "/bin/ksh"
  File /u01/orainv
     ✔  should be directory
     ✔  should be owned by "oracle"
  Kernel Parameter
     ✔  kernel.shmmax value should eq 4294967295
  Grub Config
     ∅  kernel should include "transparent_hugepage=never"
     expected ["/vmlinuz-2.6.32-696.el6.x86_64", "ro", "root=/dev/mapper/VolGroup-lv_root", "rd_NO_LUKS", "LANG=en_...=auto", "rd_LVM_LV=VolGroup/lv_root", "KEYBOARDTYPE=pc", "KEYTABLE=us", "rd_NO_DM", "rhgb", "quiet"] to include "transparent_hugepage=never"
  File /etc/grub_conf
     ∅  content should match /transparent_hugepage=never/
     expected nil to match /transparent_hugepage=never/
  Bash command
     ✔  ls -al /u01/db12201/bin stdout should match /sqlplus/
     ✔  ls -al /u01/db12201/bin exit_status should eq 0
  SQL Column
     ∅  undefined method `[]' for nil:NilClass

Test Summary: 9 successful, 3 failures, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-69>.  Please see .kitchen/logs/default-centos-69.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by aaronlippold** [comment]
Hi,

Have you tried to use the sudo: and sudo_options: in your kitchen.yml file?
i.e.

verifier:
  name: inspec
  sudo: true
  sudo_options: "-u postgres"

Is what I am using to test the postgres profiles.

Yours,

Aaron

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by pratri07** [comment]
thanks so much, i updated .kitchen.yml with this but still giving same error. do i need to do any additional sudo settings on instance created by test kitchen?

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
   name: inspec
   sudo: true
   sudo_options: "-u oracle"

platforms:
  - name: centos-6.9
  #- name: centos-7.3
    driver:
      network:
        - ["private_network", {ip: "192.168.33.8"}]

suites:
  - name: default
    driver:
        vm_hostname: chefd.local.com
    run_list:
      - recipe[oracle::default]
    verifier:
       inspec_tests:
          - test/smoke/default
    attributes:

**Comment by abielikesu** [comment]
Hi, 
Thanks to the comments in this thread, I managed to make it work.

On the database VM I have the following users:

oracle
uid=502(oracle) gid=501(oinstall) groups=501(oinstall),502(dba),504(asmdba)

dbaas (or vagrant if/when using it)
uid=500(dbaas) gid=100(users) groups=100(users),500(dbaas),502(dba)

# Make sure  the dbaas (or vagrant) user could connect to the database using sqlplus:

1. in the .bashrc, setup the ORACLE_HOME and the PATH
export ORACLE_HOME=/u01/app/oracle/database/12.1.0.2/dbhome_1
export PATH=$ORACLE_HOME/bin:$PATH

2. add the linux dbaas (or vagrant) user to the dba group
make sure to re-login for the group membership to be picked up

3. test sqlplus connection to the database
$ export ORACLE_SID=xxxx
$ sqlplus system/systempwd    # this should connect to the xxxx database

# Write the inspec file (oracle_inspec.rb)  as ...
oracle_home = '/u01/app/oracle/database/12.1.0.2/dbhome_1'

sql = oracledb_session(user: 'system', password: 'systempwd', host: 'localhost', service: 'dbservicename', sqlplus_bin: oracle_home + '/bin/sqlplus'

control 'oracle-install' do
   ... other things go here
  describe sql.query('SELECT 1 AS VALUE FROM dual;').row(0).column('value') do
    its('value') { should cmp 1 } 
  end
end

# Run inspec
inspec exec oracle_inspec.rb  -t ssh://dbaas@dbhost  ~/.ssh/db_admin.rsa

I got:

 ✔  SQL Column value should cmp == 1    


Hope this helps.

**Comment by pratri07** [comment]
Thanks for given steps and detailed info.

**## Make sure the dbaas (or vagrant) user could connect to the database using sqlplus: See my comment below.**

Even if we don't make vagrant user part of dba group, as long as database listener is running and profile is set, it can connect to database as "vagrant" os user. i made it work like this, 

**# Write the inspec file (oracle_inspec.rb) as ...See my comments below**

I've written test like this,
sql = oracledb_session( user: 'system', pass: '******', host: 'chefd.local.com', service: 'chkdb', sqlplus_bin: '/u01/db12201/bin/sqlplus' )
describe sql.query('SELECT NAME FROM v$database;').row(0).column('NAME') do
  its('value') { should cmp 'CHKDB' }
end

**# Run inspec :: See my comments below**

i ran test as oracle user and vagrant user, both working fine now.

inspec exec default/oratest.rb -t ssh://oracle@192.168.33.8 --password '*****'
[DEPRECATED] use `password` option to supply password instead of `pass`

Profile: tests from default/oratest.rb
Version: (not specified)
Target:  ssh://oracle@192.168.33.8:22


  SQL Column
     ✔  value should cmp == "CHKDB"

inspec exec default/oratest.rb -t ssh://vagrant@192.168.33.8 --password '******' 
[DEPRECATED] use `password` option to supply password instead of `pass`

Profile: tests from default/oratest.rb
Version: (not specified)
Target:  ssh://vagrant@192.168.33.8:22


  SQL Column
     ✔  value should cmp == "CHKDB"

Test Summary: 1 successful, 0 failures, 0 skipped

## My question is, when we run kitchen test command, can kitchen run inspec test as "oracle" user the way we can run using inspec exec?

**Kitchen verify also uses "vagrant" by default, don't know where we can change this settings?

See below,**

**kitchen verify**
-----> Starting Kitchen (v1.16.0)
-----> Verifying <default-centos-69>...
       Loaded tests from test/smoke/default 
[DEPRECATED] use `password` option to supply password instead of `pass`

Profile: tests from test/smoke/default
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2200


  Port 1521
     ∅  should not be listening
     expected `Port 1521.listening?` to return false, got true
  User oracle
     ✔  should exist
     ✔  uid should eq 201
     ∅  shell should eq "/bin/ksh"
     
     expected: "/bin/ksh"
          got: "/bin/bash"
     
     (compared using ==)
     
  File /u01/orainv
     ✔  should be directory
     ✔  should be owned by "oracle"
  Kernel Parameter
     ✔  kernel.shmmax value should eq 4294967295
  Grub Config
     ∅  undefined method `empty?' for nil:NilClass
  File /etc/grub_conf
     ∅  content should match /transparent_hugepage=never/
     expected nil to match /transparent_hugepage=never/
  Bash command
     ✔  ls -al /u01/db12201/bin stdout should match /sqlplus/
     ✔  ls -al /u01/db12201/bin exit_status should eq 0
  SQL Column
     ✔  value should cmp == "CHKDB"

Test Summary: 8 successful, 4 failures, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-centos-69>.  Please see .kitchen/logs/default-centos-69.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

How can we make kitchen test and kitchen verify configure run test as other user than default?
