### ISSUE TITLE
Version 2.2.101 introduced breaking changes to profile attributes

### ISSUE THREAD

**Issue by ncs-alane** [inspec/inspec#3442]
### 🎛 Description

This is a 🐛 bug report.

#3318 changed the implementation of profile attributes to require a definition in the associated profile file. This was a breaking change as attributes previously did not need to be defined before being used.

### 🌍 InSpec Version

2.2.101

### 🤔 Replication Case

Use InSpec 2.2.78 to execute a profile named `test_profile` which uses an attribute named `test_attribute` that is not defined in the profile file and see it succeed. 

Use InSpec 2.2.101 to execute the same profile and see it fail with an error like `Profile 'test_profile from {:path=>"tests/inspec"}' does not have a attribute with name 'test_attribute'`.

Define `test_attribute` in the profile file, replicate the previous step, and see it succeed.

### 💁 Possible Solutions

Implement backward compatible logic so that undefined attributes are still valid until InSpec 3.0.0 is released.

**Comment by aaronlippold** [comment]
Aaron, are you defining your attributes inside the control block or outside
the control block. I noticed this as well when I tried to Define an
attribute inside the control block which used to work fine but when I moved
it outside the control block it functioned normally again. I think this is
still a bug I just haven't had time to write up a issue on it. Perhaps this
could be a small work around.

**Comment by clintoncwolfe** [comment]
I'm pretty sure this is working as designed; it being a breaking change was not anticipated, though.

I made the argument internally that attributes are declared, set, and read as separate operations that are sometimes combined into one expression; we should be more careful about where those operations are expected and permitted.  I didn't think it made sense to declare an attribute inside a control.

Obviously people out there have a use case for that, and I was only objecting on philosophical reasons; so yes, I think we should put in something to allow declaring attrs in controls, at least in 2.x .

My apologies.

**Comment by chris-rock** [comment]
@ncs-alane is it possible to share a code example to illustrate your issue?

**Comment by ncs-alane** [comment]
@aaronlippold 
I have used `#attribute` outside of the control blocks; when I last tried using `#attribute` in a control block, it was undefined. I believe making `#attribute` available in more contexts was one of the changes with #3318.

@clintoncwolfe 
I spoke briefly with ~@cheeseplus~ @jerryaldrichiii last week about the changes in #3318 and the InSpec release process in general. My understanding is that InSpec is still intended to be adhering to semantic versioning and that this run of feature releases under 2.2.x is not intentional, but I may have misunderstood. 

I agree that it makes sense for profiles to declare attributes in the profile file, but should not be mandatory until InSpec 3 to ensure backward compatibility; I would expect `#attribute` to continue to fetch attributes that are not declared in the profile file for now. As for where `#attribute` is used in control files, I think making it available in the control blocks is a nice move to improve comprehensibility.

@chris-rock 
Yes, if necessary. I'll try to together a minimal example today.

**Comment by ncs-alane** [comment]
@chris-rock

I created a gist which demonstrates the bug.

https://gist.github.com/ncs-alane/88b6db227164d5c958a8bc6b3dd96565

**Comment by frezbo** [comment]
@ncs-alane your way of defining attribute is wrong. It should have been:

```
test_attribute = attribute "test_attribute", defualt: {}
```
If it used to work on older versions, I would say the older versions had a bug with checking for `default` value and it's fixed and working as expected in the newer version

**Comment by ncs-alane** [comment]
@frezbo 
The syntax of `attribute "test_attribute", {}` just passed an empty hash for the options argument as `#attribute` was using a positional hash argument for options, rather than keyword arguments; it was intended to omit any options, not specify the default as a hash.

Interestingly, specifying a default value does solve the problem of using an undefined attribute in InSpec 2.2.101, but that behaviour does not seem intuitive to me. In my mind, the presence or absence of a default value should not determine if the profile considers an attribute to exist, especially because the documentation indicates that default values are optional (emphasis is mine): 

> Attributes **may** contain the following options:
> Use default to set a default value for the attribute.

**Comment by clintoncwolfe** [comment]
Just to re-iterate, we do intend to follow semver, at least regarding major versions.  Sometimes we mess up (here, we removed the ability to do something we thought no one would do).  We've learned it is being used, thus should not be removed, so this is a bug, and should be fixed in the 2.x series.

**Comment by ncs-alane** [comment]
@clintoncwolfe 
Thank you for the clarification!

**Comment by ncs-alane** [comment]
Thanks for taking this on, @jerryaldrichiii!

**Comment by ncs-alane** [comment]
It appears that #3454 does not completely solve the regression. With InSpec 2.3.5, I am still seeing the same failures attempting to access attributes which are provided to the runner by way of the `:attributes` option but not defined in `inspec.yml` or in any attributes file.

**Comment by frezbo** [comment]
@ncs-alane its not `:attributes`, if using API you have to use `attributes`, its a **String**, not a **Symbol**

**Comment by ncs-alane** [comment]
@frezbo it appears to be a symbol based on https://github.com/inspec/inspec/blob/master/lib/inspec/runner.rb#L140, and did work as a symbol until the 2.2.101 release.

**Comment by frezbo** [comment]
@ncs-alane yeh it is, it only worked for me when passed as *string*. Some of therunner options are strings like `reporter` , `color` etc

**Comment by ncs-alane** [comment]
My mistake; this fix was just released with 2.3.10 and it does indeed solve the problem. Thanks again all!
